name: Deploy

on:
  push:
    branches:
      - 'main'

concurrency:
  group: main-deploy
  cancel-in-progress: true

jobs:
  cloud-run-deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agents/requirements.txt

    - id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        adk deploy cloud_run \                                                                                                                                     ─╯
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --region=${{ vars.GCP_REGION }} \
          --service_name=${{ vars.SERVICE_NAME }} \
          --with_ui \
          agents
        
